# Generated by Django 5.1 on 2024-10-23 20:51

import aulas.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='id_Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80, validators=[aulas.models.validarNome])),
                ('sexo', models.CharField(max_length=10)),
                ('raca', models.CharField(max_length=80)),
                ('especie', models.CharField(max_length=80)),
                ('pelagem', models.CharField(max_length=20)),
                ('idade', models.PositiveIntegerField()),
                ('id_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.id_tutor')),
            ],
        ),
    ]
